name: lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Lint Markdown with Prettier
      run: npx prettier **/*.md --list-different
